# Generated by Django 5.2.14 on 2026-05-23 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "species",
                    models.CharField(
                        choices=[("dog", "Dog"), ("cat", "Cat"), ("other", "Other")],
                        max_length=20,
                    ),
                ),
                ("breed", models.CharField(blank=True, max_length=100)),
                ("age_years", models.IntegerField(blank=True, null=True)),
                ("age_months", models.IntegerField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                ("description", models.TextField()),
                ("photo", models.ImageField(blank=True, upload_to="animals/")),
                (
                    "photo_url",
                    models.URLField(
                        blank=True,
                        help_text="External photo URL (used if no file uploaded)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("pending", "Adoption Pending"),
                            ("adopted", "Adopted"),
                            ("hold", "On Hold"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("intake_date", models.DateField()),
                ("is_featured", models.BooleanField(default=False)),
                ("is_good_with_kids", models.BooleanField(blank=True, null=True)),
                ("is_good_with_dogs", models.BooleanField(blank=True, null=True)),
                ("is_good_with_cats", models.BooleanField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-is_featured", "-intake_date"],
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
