# Generated by Django 5.1.15 on 2026-07-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                (
                    "summary",
                    models.TextField(
                        help_text="Short preview shown on the homepage and listings."
                    ),
                ),
                (
                    "body",
                    models.TextField(help_text="Full article body. HTML allowed."),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True, help_text="Header image URL (optional)."
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "News Post",
                "ordering": ["-published_at", "-created_at"],
            },
        ),
    ]
