# Generated by Django 5.2.14 on 2026-06-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volunteers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="volunteer",
            name="orientation_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="volunteer",
            name="orientation_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="volunteer",
            name="volunteer_type",
            field=models.CharField(
                choices=[("regular", "Regular"), ("cs", "Community Service")],
                default="regular",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="volunteerapplication",
            name="cs_hours_required",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Total community service hours required by the court",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="volunteerapplication",
            name="cs_offense_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("traffic", "Traffic / OVI"),
                    ("drug", "Drug / Substance"),
                    ("theft", "Theft / Shoplifting / Robbery"),
                    ("assault", "Assault / Disorderly Conduct"),
                    ("animal_cruelty", "Animal Cruelty / Abuse"),
                    ("property", "Property / Vandalism"),
                    ("minor", "Minor in Possession"),
                    ("domestic", "Domestic / Family"),
                    ("financial", "Financial / Fraud"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="volunteerapplication",
            name="cs_offense_description",
            field=models.TextField(
                blank=True, help_text="Additional detail about the offense or placement"
            ),
        ),
        migrations.AddField(
            model_name="volunteerapplication",
            name="cs_organization",
            field=models.CharField(
                blank=True,
                help_text="Referring court or organization name",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="volunteerapplication",
            name="is_community_service",
            field=models.BooleanField(default=False),
        ),
    ]
